Found 2920 validated image filenames belonging to 5 classes.
Found 626 validated image filenames belonging to 5 classes.
Found 626 validated image filenames belonging to 5 classes.
wandb: WARNING WandbCallback is deprecated and will be removed in a future release. Please use the WandbMetricsLogger, WandbModelCheckpoint, and WandbEvalCallback callbacks instead. See https://docs.wandb.ai/guides/integrations/keras for more information.
wandb: WARNING The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
C:\Users\lukas\anaconda3\envs\Flower_recognition_CNN\lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()
Epoch 1/30
Traceback (most recent call last):
  File "C:\Users\lukas\PycharmProjects\Flower_recodnition_CNN\custom_CNN.py", line 155, in <module>
    main()
  File "C:\Users\lukas\PycharmProjects\Flower_recodnition_CNN\custom_CNN.py", line 148, in main
    model = train_model(model, train_generator, val_generator)
  File "C:\Users\lukas\PycharmProjects\Flower_recodnition_CNN\custom_CNN.py", line 58, in train_model
    model.fit(
  File "C:\Users\lukas\anaconda3\envs\Flower_recognition_CNN\lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\lukas\anaconda3\envs\Flower_recognition_CNN\lib\site-packages\wandb\integration\keras\keras.py", line 663, in on_train_batch_end
    wandb.run.summary["graph"] = wandb.Graph.from_keras(self.model)
  File "C:\Users\lukas\anaconda3\envs\Flower_recognition_CNN\lib\site-packages\wandb\sdk\data_types\graph.py", line 357, in from_keras
    for in_layer in _nest(in_node.inbound_layers):
AttributeError: 'Node' object has no attribute 'inbound_layers'
